<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channel[
<!ELEMENT channel (item+,title,link,image*,language?,description)>
<!ATTLIST channel version CDATA #REQUIRED>
<!ELEMENT item ((title,link,description?)|(link,title,description?)|(description?,title,link))>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image ((title,link,url)|(link,title,url)|(url,title,link))>
<!ELEMENT url (#PCDATA)>
<!ELEMENT language (#PCDATA)>
]>
<channel version="1.0">
    <item>
        <title></title>
        <link></link>
        <description></description>
    </item>
    <title></title>
    <link></link>
    <image>
        <title></title>
        <link></link>
        <url></url>
    </image>
    <language></language>
    <description></description>
</channel>